{{- if and .Values.ec.ingress.enabled (not .Values.ec.gatewayApi.enabled ) (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ec.gateway.serviceAccountName" . }}
  namespace: {{ .Values.gw.namespace }}
  labels:
    {{- include "ec.labels" . | nindent 4 }}
  {{- with .Values.ec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}