apiVersion: flomesh.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  namespace: default
  name: pipy-ok
spec:
  lbType: ActiveActive
  targets:
    - clusterKey: default/default/default/cluster2
      weight: 20
    - clusterKey: default/default/default/cluster3
      weight: 30
