apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipy-sidecar-007
  labels:
    app: pipy-007
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipy-007
  template:
    metadata:
      labels:
        app: pipy-007
        sys: pipy-sidecar-samples
        tag: provider
      annotations:
        flomesh.io/inject: "true"
    spec:
      containers:
      - name: pipy-007
        image: flomesh/pipy-pjs:latest
        ports:
        - containerPort: 6080
        command: ["/usr/local/bin/pipy", "/etc/pipy/test/003-hello-ip/pipy.js", "--reuse-port"]