apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipy-sidecar-107
  labels:
    app: pipy-107
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipy-107
      sys: pipy-sidecar-samples
      mode: remote
  template:
    metadata:
      labels:
        app: pipy-107
        sys: pipy-sidecar-samples
        mode: remote
      annotations:
        flomesh.io/inject: "true"
    spec:
      containers:
      - name: pipy-107
        image: flomesh/pipy-pjs:latest
        ports:
        - containerPort: 6080
        command: ["/usr/local/bin/pipy", "/etc/pipy/test/003-hello-ip/pipy.js"]