apiVersion: flomesh.io/v1alpha1
kind: ProxyProfile
metadata:
  name: pf-200
spec:
  selector:
    matchLabels:
      sys: pipy-sidecar-samples
      tag: consumer
  namespace: default
  sidecars:
    - name: sidecar
      image: flomesh/pipy-pjs:0.4.0-118
      env:
        - name: PIPY_SIDECAR_HTTP_PORT
          value: "6090"
        - name: PIPY_SERVICE_HTTP_ADDR
          value: "127.0.0.1:6080"
    - name: logger
      image: flomesh/pipy-pjs:0.4.0-118
      env:
        - name: PIPY_SIDECAR_HTTP_PORT
          value: "9090"
  config:
    sidecar.js: |
      pipy()
        .listen(os.env.PIPY_SIDECAR_HTTP_PORT)
        .connect(() => os.env.PIPY_SERVICE_HTTP_ADDR || "127.0.0.1:8080")
    logger.js: |
      pipy()
        .listen(os.env.PIPY_SIDECAR_HTTP_PORT)
        .decodeHttpRequest()
        .replaceMessage(
          new Message('Hello!\n')
        )
        .encodeHttpResponse()