apiVersion: flomesh.io/v1alpha1
kind: ProxyProfile
metadata:
  name: pf-100
spec:
  selector:
    matchLabels:
      sys: pipy-sidecar-samples
      mode: remote
#  namespace: default
  serviceEnv:
    - name: TEST_URL
      value: "http://127.0.0.1:8080"
  sidecars:
    - name: sidecar
      env:
        - name: PIPY_SIDECAR_HTTP_PORT
          value: "6090"
        - name: PIPY_SERVICE_HTTP_ADDR
          value: "127.0.0.1:6080"
    - name: test
      startupScriptName: hello.js
      image: flomesh/pipy-pjs:0.4.0-114
      imagePullPolicy: IfNotPresent
      env:
        - name: PIPY_SIDECAR_HTTP_PORT
          value: "7090"
        - name: PIPY_HELLO_HTTP_PORT
          value: "9090"
        - name: PIPY_SERVICE_HTTP_ADDR
          value: "127.0.0.1:6080"