apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ec.configmaps.crds.name }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.labels" . | nindent 4 }}
data:
  flomesh.io_clusters.yaml: |
{{ (.Files.Get "apis/flomesh.io_clusters.yaml") | indent 4 }}
  flomesh.io_proxyprofiles.yaml: |
{{ (.Files.Get "apis/flomesh.io_proxyprofiles.yaml") | indent 4 }}
  flomesh.io_mcs-api.yaml: |
{{ (.Files.Get "apis/flomesh.io_mcs-api.yaml") | indent 4 }}
  {{- if .Values.ec.gatewayApi.enabled }}
  gateway-api.yaml: |
{{ (.Files.Get "apis/gateway-api.yaml") | indent 4 }}
  {{- end }}
  {{- if .Values.ec.ingress.namespaced }}
  flomesh.io_namespacedingresses.yaml: |
{{ (.Files.Get "apis/flomesh.io_namespacedingresses.yaml") | indent 4 }}
  {{- end }}
