{{- if .Values.ec.egressGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: erie-canal-egress-gateway
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.egress-gateway.labels" . | nindent 4 }}
spec:
  ports:
    - port: 1080
      name: pipy-socks-port
      targetPort: 1080
      protocol: TCP
      appProtocol: tcp
  selector:
    {{- include "ec.egress-gateway.selectorLabels" . | nindent 4 }}
{{- end }}