{{- if .Values.ec.egressGateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: erie-canal-egress-gateway-pjs
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.egress-gateway.labels" . | nindent 4 }}
data:
  pipy-sock.js: |
    // version: '2022.09.03'
    ((
      socksActiveConnectionGauge = new stats.Gauge('socks_active_connection', ['source_address', 'destination_address', 'destination_port']),
      socksTotalConnectionCounter = new stats.Counter('socks_total_connection', ['source_address', 'destination_address', 'destination_port']),
      socksSendBytesTotalCounter = new stats.Counter('socks_send_bytes_total', ['source_address', 'destination_address', 'destination_port']),
      socksReceiveBytesTotalCounter = new stats.Counter('socks_receive_bytes_total', ['source_address', 'destination_address', 'destination_port']),
      serverLiveGauge = (new stats.Gauge('sidecar_server_live')).increase(),
      logLogging = new logging.JSONLogger('access-logging').toFile('/dev/stdout').log,
      prometheusTarget = '127.0.0.1:6060'
    ) => pipy({
      _id: null,
      _host: null,
      _port: null,
      _sourceIP: null,
      _protocol: null,
      _logDataStruct: null
    })
    
      //
      // Socks5 server
      //
      .listen(1080)
      .onStart(
        () => (
          _host = null,
          _logDataStruct = {},
          _id = algo.uuid().substring(0, 18).replaceAll('-', ''),
          _logDataStruct['id'] = _id,
          _logDataStruct['start_time'] = (new Date()).toISOString(),
          _logDataStruct['source_address'] = _sourceIP = __inbound.remoteAddress,
          _logDataStruct['source_port'] = __inbound.remotePort,
          null
        )
      )
      .onEnd(
        () => (
          _host && socksActiveConnectionGauge.withLabels(_sourceIP, _host, _port).decrease(),
          _logDataStruct['end_time'] = (new Date()).toISOString(),
          logLogging(_logDataStruct)
        )
      )
      .acceptSOCKS(
        (host, port) => (
          _logDataStruct['destination_address'] = _host = host,
          _logDataStruct['destination_port'] = _port = port,
          socksActiveConnectionGauge.withLabels(_sourceIP, _host, _port).increase(),
          socksTotalConnectionCounter.withLabels(_sourceIP, _host, _port).increase(),
          true
        )
      )
      .to($ => $
        .onStart(
          () => new Data
        )
        .fork('logger-requests')
        .handleData(
          data => (
            socksSendBytesTotalCounter.withLabels(_sourceIP, _host, _port).increase(data.size)
          )
        )
        .connect(
          () => _host + ':' + _port
        )
        .handleData(
          data => (
            socksReceiveBytesTotalCounter.withLabels(_sourceIP, _host, _port).increase(data.size)
          )
        )
      )
    
      //
      // Logging HTTP requests
      //
      .pipeline('logger-requests')
      .onStart(
        () => (
          _protocol = undefined,
          new Data
        )
      )
      .detectProtocol(
        protocolName => _protocol = protocolName
      )
      .branch(
        () => _protocol === 'HTTP', $ => $
          .demuxHTTP().to($ => $
            .handleMessageStart(
              msg => (
                ((request) => (
                  request = {
                    connection_id: _logDataStruct.id,
                    request_time: (new Date()).toISOString(),
                    source_address: _logDataStruct['source_address'],
                    source_port: _logDataStruct['source_port'],
                    host: msg.head.headers.host,
                    path: msg.head.path,
                    method: msg.head.method
                  },
                  logLogging(request)
                ))()
              )
            )
          ),
        () => _protocol === 'TLS', $ => $
          .handleTLSClientHello(
            (hello) => (
              _logDataStruct['serverNames'] = hello.serverNames,
              _logDataStruct['protocolNames'] = hello.protocolNames
            )
          ),
        () => _protocol === '', $ => $
      )
      .dummy()
    
      //
      // Prometheus collects metrics
      //
      .listen(15010)
      .demuxHTTP()
      .to($ => $
        .handleMessageStart(
          msg => (
            (msg.head.path === '/stats/prometheus' && (msg.head.path = '/metrics')) || (msg.head.path = '/stats' + msg.head.path)
          )
        )
        .muxHTTP(() => prometheusTarget)
        .to($ => $
          .connect(() => prometheusTarget)
        )
      )
    
    )()
{{- end }}