{{- if .Values.ec.egressGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ec.egressGateway.name }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.egress-gateway.labels" . | nindent 4 }}
    {{- include "ec.egress-gateway.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ec.egressGateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "ec.egress-gateway.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "ec.egress-gateway.labels" . | nindent 8 }}
        {{- include "ec.egress-gateway.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/path: '/stats/prometheus'
        prometheus.io/port: '15010'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: pipy
        image: {{ include "ec.pipy-repo.image" . }}
        imagePullPolicy: {{ .Values.ec.image.pullPolicy }}
        resources:
          {{- toYaml .Values.ec.egressGateway.resources | nindent 10 }}
        volumeMounts:
          - name: {{ .Values.ec.configmaps.egress.name }}
            mountPath: "/repo/egress-gateway.js"
            subPath: egress-gateway.js
            readOnly: true
        ports:
          - name: "egress-nat-port"
            containerPort: {{ .Values.ec.egressGateway.port }}
          - name: "pipy-admin-port"
            containerPort: {{ .Values.ec.egressGateway.adminPort }}
        command:
          - pipy
        args:
          - "/repo/egress-gateway.js"
          - "--log-level={{ .Values.ec.egressGateway.logLevel }}"
          - "--admin-port={{ .Values.ec.egressGateway.adminPort }}"
        env:
          {{- include "ec.common-env" . | nindent 10 }}
      volumes:
        - name: {{ .Values.ec.configmaps.egress.name }}
          configMap:
            name: {{ .Values.ec.configmaps.egress.name }}
      serviceAccountName: {{ include "ec.serviceAccountName" . }}
      {{- with .Values.ec.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}