{{- if .Values.ec.egressGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: erie-canal-egress-gateway
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.egress-gateway.labels" . | nindent 4 }}
  annotations:
    {{- include "ec.egress-gateway.annotations" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ec.egressGateway.port }}
      name: egress-nat-port
      targetPort: {{ .Values.ec.egressGateway.port }}
      protocol: TCP
      appProtocol: tcp
  selector:
    {{- include "ec.egress-gateway.selectorLabels" . | nindent 4 }}
{{- end }}