apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ErieCanal.services.manager.name }}
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ErieCanal.services.webhook.type }}
  ports:
  - name: health
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    {{- include "ErieCanal.manager.selectorLabels" . | nindent 4 }}