{{- if and .Values.ec.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: pipy
  labels:
    {{- include "ec.labels" . | nindent 4 }}
  annotations:
    meta.flomesh.io/namespace: {{ include "ec.namespace" . }}
    meta.flomesh.io/ingress-pipy-svc: {{ .Values.ec.ingress.service.name }}
spec:
  controller: flomesh.io/ingress-pipy
{{- end }}