apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: erie-canal-leader-election-rolebinding
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: erie-canal-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "ErieCanal.serviceAccountName" . }}
  namespace: {{ include "ErieCanal.namespace" . }}