apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ErieCanal.configmaps.manager.name }}
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
data:
  {{ .Values.ErieCanal.configmaps.manager.filename }}: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceNamespace: {{ include "ErieCanal.namespace" . }}
      resourceName: manager.flomesh.io
