apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ErieCanal.configmaps.manifests.name }}
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
data:
  cluster_local.yaml: |-
{{ (.Files.Get "components/cluster_local.yaml") | indent 4 }}
  default_proxyprofile.yaml: |-
{{ (.Files.Get "components/default_proxyprofile.yaml") | indent 4 }}
