apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: erie-canal-mesh-config-role
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch