apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ec.configmaps.mesh.name }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.labels" . | nindent 4 }}
data:
  mesh_config.json: |-
    {
      "isManaged": false,

      "images": {
        "repository": "{{ .Values.ec.image.repository }}",
        "pipyImage": {{ include "ec.pipy.image.wo-repo" . | quote }},
        "proxyInitImage": {{ include "ec.proxy-init.image.wo-repo" . | quote }},
        "klipperLbImage": {{ include "ec.service-lb.image.wo-repo" . | quote }}
      },

      "repo": {
        "rootUrl": {{ include "ec.repo-service.url" . | quote }}
      },

      "webhook": {
        "serviceName": "{{ .Values.ec.services.webhook.name }}"
      },

      "ingress": {
        "enabled": {{ and .Values.ec.ingress.enabled (not .Values.ec.gatewayApi.enabled )}},
        "namespaced": {{ .Values.ec.ingress.namespaced }},
        "http": {
          "enabled": {{ .Values.ec.ingress.http.enabled }},
          "bind": {{ .Values.ec.ingress.http.port }},
          "listen": {{ .Values.ec.ingress.http.containerPort }},
          "nodePort": {{ default 0 .Values.ec.ingress.http.nodePort }}
        },
        "tls": {
          "enabled": {{ .Values.ec.ingress.tls.enabled }},
          "bind": {{ .Values.ec.ingress.tls.port }},
          "listen": {{ .Values.ec.ingress.tls.containerPort }},
          "nodePort": {{ default 0 .Values.ec.ingress.tls.nodePort }},
          "mTLS": {{ .Values.ec.ingress.tls.mTLS }},
          "sslPassthrough": {
            "enabled": {{ .Values.ec.ingress.tls.sslPassthrough.enabled }},
            "upstreamPort": {{ .Values.ec.ingress.tls.sslPassthrough.upstreamPort }}
          }
        }
      },

      "gatewayApi": {
        "enabled": {{ and .Values.ec.gatewayApi.enabled (not .Values.ec.ingress.enabled) }}
      },

      "certificate": {
        {{- if .Values.certManager.enabled }}
        "manager": "cert-manager",
        {{- else }}
        "manager": "archon",
        {{- end }}
        "caBundleName": "{{ .Values.ec.certificate.caBundleName }}",
        "caBundleNamespace": ""
      },

      "cluster": {
        "uid": "",
        "region": "default",
        "zone": "default",
        "group": "default",
        "name": "local",
        "controlPlaneUID": ""
      },

      "serviceLB": {
        "enabled": {{ .Values.ec.serviceLB.enabled }}
      },

      "featuresGate": {
        "createServiceAndEndpointSlicesForMCS": {{ .Values.ec.featuresGate.createEndpointSliceForMCS }}
      }
    }