apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ec.configmaps.mesh.name }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.labels" . | nindent 4 }}
data:
  mesh_config.json: |-
    {
      "isManaged": false,

      "images": {
        "repository": "{{ .Values.ec.image.repository }}",
        "pipyImage": {{ include "ec.pipy.image.wo-repo" . | quote }},
        "proxyInitImage": {{ include "ec.proxy-init.image.wo-repo" . | quote }},
        "klipperLbImage": {{ include "ec.service-lb.image.wo-repo" . | quote }}
      },

      "repo": {
        "rootUrl": {{ include "ec.repo-service.url" . | quote }}
      },

      "webhook": {
        "serviceName": "{{ .Values.ec.services.webhook.name }}"
      },

      "ingress": {
        "enabled": {{ .Values.ec.ingress.enabled }},
        "namespaced": {{ .Values.ec.ingress.namespaced }},
        "tls": {
          "enabled": {{ .Values.ec.ingress.tls.enabled }},
          "sslPassthrough": {
            "enabled": {{ .Values.ec.ingress.tls.sslPassthrough.enabled }},
            "upstreamPort": {{ .Values.ec.ingress.tls.sslPassthrough.upstreamPort }}
          }
        }
      },

      "gatewayApi": {
        "enabled": {{ .Values.ec.gatewayApi.enabled }}
      },

      "certificate": {
        {{- if .Values.certManager.enabled }}
        "manager": "cert-manager"
        {{- else }}
        "manager": "archon"
        {{- end }}
      },

      "cluster": {
        "region": "default",
        "zone": "default",
        "group": "default",
        "name": "local"
      },

      "serviceLB": {
        "enabled": {{ .Values.ec.serviceLB.enabled }}
      }
    }