apiVersion: batch/v1
kind: Job
metadata:
  name: erie-canal-pre-delete
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: erie-canal-pre-delete
      labels:
        {{- include "ErieCanal.labels" . | nindent 8 }}
    spec:
      containers:
      - name: uninstall
        image: {{ include "ErieCanal.toolbox.image" . }}
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          kubectl delete namespacedingresses.flomesh.io --all -A
          kubectl delete serviceimports.flomesh.io --all -A
          kubectl delete serviceexports.flomesh.io --all -A
          kubectl delete proxyprofiles.flomesh.io --all
          kubectl delete clusters.flomesh.io --all
          kubectl delete -f /crds/
        volumeMounts:
        - mountPath: /manifests
          name: {{ .Values.ErieCanal.configmaps.manifests.name }}
        - mountPath: /crds
          name: {{ .Values.ErieCanal.configmaps.crds.name }}
      volumes:
      - configMap:
          name: {{ .Values.ErieCanal.configmaps.manifests.name }}
        name: {{ .Values.ErieCanal.configmaps.manifests.name }}
      - configMap:
          name: {{ .Values.ErieCanal.configmaps.crds.name }}
        name: {{ .Values.ErieCanal.configmaps.crds.name }}
      restartPolicy: Never
      serviceAccountName: {{ include "ErieCanal.serviceAccountName" . }}
      {{- with .Values.ErieCanal.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ErieCanal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ErieCanal.affinity.enabled }}
      affinity:
        {{- with .Values.ErieCanal.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.ErieCanal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}