apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ec.configmaps.repoInit.name }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.labels" . | nindent 4 }}
binaryData:
  scripts.tar.gz: |
{{ (.Files.Get "components/scripts.tar.gz") | b64enc | indent 4}}