apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ErieCanal.configmaps.repoInit.name }}
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
binaryData:
  scripts.tar.gz: |
{{ (.Files.Get "components/scripts.tar.gz") | b64enc | indent 4}}