{{- if not .Values.ec.repo.preProvision.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ec.repo.name }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.repo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ec.repo.replicaCount }}
  selector:
    matchLabels:
      {{- include "ec.repo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ec.repo.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ec.repo.labels" . | nindent 8 }}
        {{- include "ec.repo.selectorLabels" . | nindent 8 }}
        {{- with .Values.ec.repo.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: repo
        image: {{ include "ec.pipy.image" . }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: repo
          containerPort: {{ .Values.ec.services.repo.containerPort }}
        command:
        - sh
        - -c
        - |
          /usr/local/bin/pipy --admin-port={{ .Values.ec.services.repo.port }}
        resources:
          {{- toYaml .Values.ec.repo.resources | nindent 10 }}
        env:
          {{- include "ec.common-env" . | nindent 10 }}
        livenessProbe:
          initialDelaySeconds: 1
          timeoutSeconds: 5
          tcpSocket:
            port: {{ .Values.ec.services.repo.port }}
        readinessProbe:
          initialDelaySeconds: 1
          timeoutSeconds: 5
          tcpSocket:
            port: {{ .Values.ec.services.repo.port }}
        {{- with .Values.ec.repo.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 30
      {{- with .Values.ec.repo.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ec.serviceAccountName" . }}
      {{- with .Values.ec.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ec.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ec.affinity.enabled }}
      affinity:
        {{- with .Values.ec.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: flomesh.io/app
                  operator: In
                  values:
                  - {{ .Values.ec.repo.name}}
              topologyKey: kubernetes.io/hostname
            weight: 100
      {{- end }}
      {{- with .Values.ec.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}