{{- if not .Values.ErieCanal.repo.preProvision.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ErieCanal.services.repo.name }}
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.repo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ErieCanal.services.repo.type }}
  ports:
  - name: repo
    port: {{ .Values.ErieCanal.services.repo.port }}
    protocol: TCP
    targetPort: repo
  selector:
    {{- include "ErieCanal.repo.selectorLabels" . | nindent 4 }}
{{- end }}