{{- if .Values.ErieCanal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ErieCanal.serviceAccountName" . }}
  namespace: {{ include "ErieCanal.namespace" . }}
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
  {{- with .Values.ErieCanal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
