{{- if .Values.ec.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ec.serviceAccountName" . }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.labels" . | nindent 4 }}
  {{- with .Values.ec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
