apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ec.services.webhook.name }}
  namespace: {{ include "ec.namespace" . }}
  labels:
    {{- include "ec.manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ec.services.webhook.type }}
  ports:
  - name: webhook
    port: {{ .Values.ec.services.webhook.port }}
    protocol: TCP
    targetPort: webhook
  selector:
    {{- include "ec.webhook-service.selectorLabels" . | nindent 4 }}