apiVersion: flomesh.io/v1alpha1
kind: NamespacedIngress
metadata:
  name: namespaced-ingress-101
  namespace: test-100
spec:
  serviceType: LoadBalancer
  ports:
  - name: http
    port: 101
    protocol: TCP
    nodePort: 30101