apiVersion: flomesh.io/v1alpha1
kind: NamespacedIngress
metadata:
  name: namespaced-ingress-102
  namespace: test-100
spec:
  serviceType: LoadBalancer
  http:
    port:
      name: http
      port: 102
      nodePort: 30102
  tls:
    enabled: true
    port:
      name: https
      port: 1443
    sslPassthrough:
      enabled: true
      upstreamPort: 443
  env:
  - name: a1
    value: abc
  - name: b1
    value: xyz
  - name: c1
    value: nnn
  serviceAnnotations:
    flomesh.io/test1: erie-canal-1
    flomesh.io/test2: erie-canal-2
    flomesh.io/test3: erie-canal-3
  resources:
    limits:
      cpu: 1234m
      memory: 521Mi
    requests:
      cpu: 123m
      memory: 17M
  nodeSelector:
    ingress-ready: "yes"
  logLevel: 5
  podAnnotations:
    flomesh.io/anno1: erie-canal-1
    flomesh.io/anno2: erie-canal-2
    flomesh.io/anno3: erie-canal-3

