kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster2
nodes:
  - role: control-plane
    image: kindest/node:v1.21.12
    extraPortMappings:
      - containerPort: 80
        hostPort: 8092
        protocol: TCP
networking:
  apiServerAddress: 10.0.1.21
  apiServerPort: 6447