apiVersion: flomesh.io/v1alpha1
kind: ProxyProfile
metadata:
  name: nacos-pf
spec:
  mode: Remote
  selector:
    matchLabels:
      sys: pipy-sidecar-samples
      tag: provider
  namespace: cluster1
  sidecars:
  - name: sidecar
    env:
    - name: PIPY_SIDECAR_HTTP_PORT
      value: "6090"
    - name: PIPY_SERVICE_HTTP_ADDR
      value: "127.0.0.1:6080"