---
apiVersion: v1
kind: Namespace
metadata:
  name: pipy-echo
  labels:
    flomesh.io/inject: "true"

---
apiVersion: flomesh.io/v1alpha1
kind: ProxyProfile
metadata:
  name: restart-always
spec:
  mode: Remote
  selector:
    matchLabels:
      app: pipy-echo
  namespace: pipy-echo
  restartPolicy: Always
  sidecars:
  - name: sidecar

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipy-echo
  name: pipy-echo
  namespace: pipy-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipy-echo
  template:
    metadata:
      labels:
        app: pipy-echo
    spec:
      containers:
      - image: flomesh/pipy:0.30.0-158-echo
        name: pipy
        ports:
        - containerPort: 8080