{{- if and .Values.ec.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if .Values.ec.ingress.namespaced }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Values.ec.ingress.name .Values.nsig.metadata.namespace }}
  namespace: {{ .Values.nsig.metadata.namespace }}
  labels:
    {{- include "ec.ingress-pipy.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.nsig.spec.replicas }}
  selector:
    matchLabels:
      {{- include "ec.ingress-pipy.selectorLabels" . | nindent 6 }}
      ingress.flomesh.io/namespaced: {{ .Values.ec.ingress.namespaced | quote }}
      ingress.flomesh.io/ns: {{ .Values.nsig.metadata.namespace }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "ec.ingress-pipy.labels" . | nindent 8 }}
        {{- include "ec.ingress-pipy.selectorLabels" . | nindent 8 }}
        ingress.flomesh.io/namespaced: {{ .Values.ec.ingress.namespaced | quote }}
        ingress.flomesh.io/ns: {{ .Values.nsig.metadata.namespace }}
      {{- with .Values.nsig.spec.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
      - name: wait-manager
        image: {{ include "ec.curl.image" . }}
        imagePullPolicy: IfNotPresent
        command:
          - curl
          - {{ printf "http://%s:8081/healthz" (include "ec.manager.host" .) }}
          - --connect-timeout
          - "2"
          - --retry
          - "50"
          - --retry-connrefused
          - --retry-delay
          - "5"
      containers:
      - name: ingress
        image: {{ printf "%s/%s:%s" .Values.ec.image.repository .Values.ec.ingress.name (include "ec.app-version" .) }}
        imagePullPolicy: {{ .Values.ec.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ default .Values.ec.ingress.http.containerPort .Values.nsig.spec.http.port.targetPort }}
          - name: https
            containerPort: {{ default .Values.ec.ingress.tls.containerPort .Values.nsig.spec.tls.port.targetPort }}
          - name: health
            containerPort: 8081
        args:
          - --v={{ default .Values.ec.logLevel .Values.nsig.spec.logLevel }}
        env:
          {{- include "ec.common-env" . | nindent 10 }}
          {{- with .Values.nsig.spec.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- if .Values.nsig.spec.resources }}
        resources:
          {{- toYaml .Values.nsig.spec.resources | nindent 10 }}
        {{- else }}
        {{- with .Values.ec.ingress.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- with .Values.ec.ingress.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          tcpSocket:
            port: {{ .Values.ec.ingress.http.containerPort }}
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          tcpSocket:
            port: {{ .Values.ec.ingress.http.containerPort }}
      terminationGracePeriodSeconds: 60
      serviceAccountName: {{ include "ec.namespaced-ingress.serviceAccountName" . }}
      {{- with .Values.ec.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.nsig.spec.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nsig.spec.nodeSelector | nindent 8 }}
      {{- else }}
      {{- with .Values.ec.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.ec.affinity.enabled }}
      {{- if .Values.nsig.spec.affinity }}
      affinity:
        {{- toYaml .Values.nsig.spec.affinity | nindent 8 }}
      {{- else }}
      affinity:
        {{- with .Values.ec.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: flomesh.io/app
                      operator: In
                      values:
                        - {{ printf "%s-%s" .Values.ec.ingress.name .Values.nsig.metadata.namespace }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- end }}
      {{- end }}
      {{- if .Values.nsig.spec.tolerations }}
      tolerations:
        {{- toYaml .Values.nsig.spec.tolerations | nindent 8 }}
      {{- else }}
      {{- with .Values.ec.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}