{{- if and .Values.ErieCanal.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if .Values.ErieCanal.ingress.namespaced }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ErieCanal.namespaced-ingress.serviceAccountName" . }}
  namespace: {{ .Values.nsig.metadata.namespace }}
  labels:
    {{- include "ErieCanal.labels" . | nindent 4 }}
  {{- with .Values.ErieCanal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
