{{- if and .Values.ec.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if .Values.ec.ingress.namespaced }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ec.namespaced-ingress.serviceAccountName" . }}
  namespace: {{ .Values.nsig.metadata.namespace }}
  labels:
    {{- include "ec.labels" . | nindent 4 }}
  {{- with .Values.ec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
